packages:
  - .

allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  argon2: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - argon2
  - esbuild
  - prisma
  - unrs-resolver
